//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urfu.AuthorDetector.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BayesClassifierTest
    {
        public int Id { get; set; }
        public bool Success { get; set; }
        public double FirstToAll { get; set; }
        public Nullable<double> FirstToSecond { get; set; }
        public int MessageCount { get; set; }
        public Nullable<int> MessagesLength { get; set; }
    
        public virtual ClassifierVersion ClassifierVersion { get; set; }
    }
}
