//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urfu.AuthorDetector.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassifierVersion
    {
        public ClassifierVersion()
        {
            this.ClassifierResult = new HashSet<ClassifierResult>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ClassifierResult> ClassifierResult { get; set; }
    }
}
