//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urfu.AuthorDetector.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassifierResult
    {
        public ClassifierResult()
        {
            this.ClassifierParams = new HashSet<ClassifierParams>();
        }
    
        public int Id { get; set; }
        public int RoundCount { get; set; }
        public int TestsPerRound { get; set; }
        public int MessageCount { get; set; }
        public int LearningCount { get; set; }
        public System.DateTime DateTime { get; set; }
        public double Result { get; set; }
    
        public virtual ClassifierVersion ClassifierVersion { get; set; }
        public virtual ICollection<ClassifierParams> ClassifierParams { get; set; }
    }
}
