//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urfu.AuthorDetector.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forum
    {
        public Forum()
        {
            this.Theme = new HashSet<Theme>();
            this.Author = new HashSet<Author>();
        }
    
        public int Id { get; set; }
        public string ForumUrl { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Theme> Theme { get; set; }
        public virtual ICollection<Author> Author { get; set; }
    }
}
