//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urfu.AuthorDetector.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public int IdOnForum { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Theme Theme { get; set; }
    }
}
