//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Data.Entity;
namespace Urfu.AuthorDetector.DataLayer
{
    using System;
    using System.Linq;
    
    public interface IStatisticsContext : IDisposable
    {   
    
    	void SaveChanges();
    
        void Add<T>(T entity) where T : class;
    
    
    
       
    
    	IDbSet<Post> Posts	{ get; }
    
       
    
    	IDbSet<Theme> Themes	{ get; }
    
       
    
    	IDbSet<Author> Authors	{ get; }
    
       
    
    	IDbSet<Forum> ForumSet	{ get; }
    
    }
}
